AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {{same.project_name.lower().replace(' ', '-')}} serverless application
Globals:
  Function:
    Timeout: 3
    Handler: app.lambdaHandler
    Runtime: nodejs8.10
    Tracing: Active

Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Events:
        Service:
          Type: Api
          Properties:
            Path: /
            Method: get


Outputs:
  ServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"